### ISSUE TITLE
Map not movable when notes dialog open

### ISSUE THREAD

**Issue by anfo55** [gruppe-adler/grad-leaveNotes#12]
The answer to this is probably my ignorance about the limitations Arma 3 places on dialogs functionality. For instance in map screen when notes dialog is open, map is no longer controllable until notes dialog is closed. I assume this is not changeable?

**Comment by McDiod** [comment]
You can open the notes dialog in map screen? 😄 

Not fixable as far as I know.

**Comment by anfo55** [comment]
Yes notes can be opened, but you can't edit or move map around while it is. I think this is an Arma 3 limitation rather than issue with notes?

**Comment by McDiod** [comment]
>I think this is an Arma 3 limitation rather than issue with notes?

Yes
