### ISSUE TITLE
inspect note

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/grad-leaveNotes#5]
Jeder Spieler bekommt bei Spielstart eine "Handschrift", die von ~3 zufälligen Adjektiven beschrieben wird. Mit "inspect note" kann man diese von einer Note abrufen. --> Gefundene Notes können verglichen werden, um zu sehen ob sie vom gleichen Autor sind.

**Comment by nomisum** [comment]
woot LOL, jetzt gehts ja ab.

d.h. jeder spieler hat 3 random adjektive "handschrift" ?

**Comment by McDiod** [comment]
Habs doch anders gemacht. Jeder Spieler bekommt eine von 48 möglichen Handschriften aus Adjektiv + Modifikator:

https://github.com/gruppe-adler/grad-leaveNotes/blob/handwriting/functions/fn_setHandwriting.sqf

**Comment by McDiod** [comment]
07a9a6f3f3b2ea353fec3f63ada0736207133e23
