### ISSUE TITLE
Mistake in install notes

### ISSUE THREAD

**Issue by anfo55** [gruppe-adler/grad-leaveNotes#9]
I changed `node_modules\` to `modules\` in description.ext appendages to resolve

**Comment by Fusselwurm** [comment]
ah, yes. we should make that difference between npm/manual install a bit more clear

**Comment by nomisum** [comment]
I suggest we just recommend to name the folder `node_modules` in any case. Why bother making a difference.

**Comment by Fusselwurm** [comment]
yes, I think the "modules" thingy is just a leftover from the thing I forked grad-loadouts from ^^

**Comment by McDiod** [comment]
fixed in 2.2.1 i think
